#!/bin/bash

# ===============================
# 1. Create project directories
# ===============================
mkdir -p Raw_Data QC_Reports Alignment Variant_Calling Reference

# ===============================
# 2. Update system
# ===============================
sudo apt update

# ===============================
# 3. Download Raw FASTQ Files
# ===============================
cd Raw_Data/

echo "Downloading FASTQ files..."
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR574/003/ERR5743893/ERR5743893_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR574/003/ERR5743893/ERR5743893_2.fastq.gz

# ===============================
# 4. Install Required Tools
# ===============================
cd ..
echo "Installing tools..."
sudo apt install -y fastqc bwa samtools bamtools bcftools vcftools freebayes

# ===============================
# 5. Run Quality Check (FastQC)
# ===============================
echo "Running FastQC..."
fastqc Raw_Data/ERR5743893_1.fastq.gz --outdir QC_Reports
fastqc Raw_Data/ERR5743893_2.fastq.gz --outdir QC_Reports

# ===============================
# 6. Unzip FASTQ files
# ===============================
echo "Unzipping FASTQ files..."
gunzip Raw_Data/ERR5743893_1.fastq.gz
gunzip Raw_Data/ERR5743893_2.fastq.gz

# ===============================
# 7. Download Reference Genome
# ===============================
echo "Downloading reference genome..."
wget "https://www.ebi.ac.uk/ena/browser/api/fasta/MN908947.3?download=true" -O Reference/MN908947.fasta

# ===============================
# 8. Index Reference Genome
# ===============================
echo "Indexing reference..."
bwa index Reference/MN908947.fasta
samtools faidx Reference/MN908947.fasta

# ===============================
# 9. Alignment using BWA
# ===============================
echo "Running BWA alignment..."
bwa mem Reference/MN908947.fasta \
    Raw_Data/ERR5743893_1.fastq \
    Raw_Data/ERR5743893_2.fastq \
    > Alignment/ERR5743893.sam

# ===============================
# 10. Convert SAM to BAM
# ===============================
echo "Converting SAM to BAM..."
samtools view -@ 4 -S -b Alignment/ERR5743893.sam > Alignment/ERR5743893.bam

# ===============================
# 11. Sort and Index BAM
# ===============================
echo "Sorting BAM file..."
samtools sort -@ 4 -o Alignment/ERR5743893.sorted.bam Alignment/ERR5743893.bam

echo "Indexing BAM file..."
samtools index Alignment/ERR5743893.sorted.bam

# ===============================
# 12. Variant Calling with FreeBayes
# ===============================
echo "Running FreeBayes variant calling..."
freebayes -f Reference/MN908947.fasta \
    Alignment/ERR5743893.sorted.bam \
    > Variant_Calling/ERR5743893.vcf

# ===============================
# 13. Save command history
# ===============================
history > commands.txt

echo "Pipeline completed successfully!"

